baseURL = 'https://blogbyyulia.org/'
languageCode = 'en-us'
title = 'Programming Polyglot'
theme = 'PaperMod'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Ambiguity'
    pageRef = '/posts/syntactic-ambiguity/'
    weight = 20
  [[menus.main]]
    name = 'E-commerce Churn'
    pageRef = '/posts/ecommerce-churn-prediction/'
    weight = 30
